using Blazored.LocalStorage;
using System.Net.Http.Headers;

namespace BookStoreApp.Blazor.Server.UI.Services.Base
{
	public class BaseHttpServices
	{
		private readonly IClient client;
		private readonly ILocalStorageService localstorage;

		public BaseHttpServices(IClient client, ILocalStorageService localstorage)
		{
			this.client = client;
			this.localstorage = localstorage;
		}

		// =Guid is type of array ID= (global unique)
		// The GUID data type is a 16 byte binary data type.This data type is used for the global
		// identification of objects, programs, records, and so on.The important property of a GUID
		// is that each value is globally unique. The value is generated by an algorithm, developed by Microsoft, which assures this uniqueness.
		protected Response<Guid> ConvertApiExceptions<Guid>(ApiException apiException)
		{
			if (apiException.StatusCode == 400)
			{
				return new Response<Guid>
				{
					Message = "Validation errors have occured.",
					ValidationErrors = apiException.Response,
					Success = false
				};
			}

			if (apiException.StatusCode == 404)
			{
				return new Response<Guid>
				{
					Message = "The requested item couldn't be found.",
					Success = false
				};
			}

			if (apiException.StatusCode >= 200 && apiException.StatusCode <= 299)
			{
				return new Response<Guid>
				{
					Message = "Operation reported success!",
					Success = true
				};
			}

			return new Response<Guid> { Message = "Something went wrong, please try again.", Success = false };
		}

		// Just to provide/input the bearer token into the Headers
		protected async Task GetBearerToken()
		{
            // jika menggunakan bearer, saat di-set "breakpoints (titik merah)", akan menjadi 2 arguments, Parameter & Scheme. dan ada string aneh karena parsing
            //var token = await localstorage.GetItemAsStringAsync("accessToken");
            var token = await localstorage.GetItemAsync<string>("accessToken");

			if (token != null)
			{
				client.HttpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("bearer", token);
			}
		}
	}
}
